# Generated by Django 4.0.4 on 2022-05-20 23:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cod_cliente', models.SmallAutoField(primary_key=True, serialize=False, unique=True, verbose_name='Código de Cliente')),
                ('status_cliente', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='', max_length=1, verbose_name='Status')),
                ('tipo_cliente', models.CharField(choices=[('F', 'Pessoa Fisica'), ('J', 'Pessoa Juridica')], default='', max_length=1, verbose_name='Tipo do Cliente')),
                ('nome_completo_cliente', models.CharField(max_length=155, verbose_name='Nome do Cliente')),
                ('cpf_cliente', models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='CPF')),
                ('cnpj_cliente', models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='CNPJ')),
                ('telefone1_cliente', models.CharField(blank=True, max_length=25, null=True, verbose_name='Telefone Fixo')),
                ('telefone2_cliente', models.CharField(blank=True, max_length=25, null=True, verbose_name='Telefone Celular')),
                ('rua_endereco_cliente', models.CharField(max_length=155, verbose_name='Endereço')),
                ('numero_endereco_cliente', models.CharField(max_length=10, verbose_name='Número')),
                ('cep_cliente', models.CharField(default='', max_length=9, verbose_name='CEP')),
                ('complemento_endereco_cliente', models.CharField(blank=True, max_length=155, null=True, verbose_name='Complemento')),
                ('bairro_endereco_cliente', models.CharField(max_length=155, verbose_name='Bairro')),
                ('email_cliente', models.EmailField(max_length=254, verbose_name='E-mail')),
            ],
        ),
        migrations.CreateModel(
            name='Forma_Pagamento',
            fields=[
                ('cod_forma_pagamento', models.SmallAutoField(primary_key=True, serialize=False, unique=True)),
                ('nome_forme_pagamento', models.CharField(max_length=50)),
                ('prazo_forma_pagamento', models.IntegerField()),
                ('estilo_forma_pagamento', models.CharField(blank=True, choices=[('A', 'A vista'), ('P', 'A prazo')], default='', max_length=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('cod_fornecedor', models.SmallAutoField(primary_key=True, serialize=False, unique=True)),
                ('status_fornecedor', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='', max_length=1)),
                ('tipo_fornecedor', models.CharField(choices=[('F', 'Pessoa Fisica'), ('J', 'Pessoa Juridica')], default='', max_length=1)),
                ('nome_fornecedor', models.CharField(max_length=155)),
                ('cpf_fornecedor', models.CharField(blank=True, max_length=14, null=True, unique=True)),
                ('cnpj_fornecedor', models.CharField(blank=True, max_length=18, null=True, unique=True)),
                ('telefone1_fornecedor', models.CharField(blank=True, max_length=25, null=True)),
                ('telefone2_fornecedor', models.CharField(blank=True, max_length=25, null=True)),
                ('rua_endereco_fornecedor', models.CharField(max_length=155)),
                ('numero_endereco_fornecedor', models.CharField(max_length=10)),
                ('complemento_endereco_fornecedor', models.CharField(max_length=155)),
                ('bairro_endereco_fornecedor', models.CharField(max_length=155)),
                ('email_fornecedor', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Grupo_Produtos',
            fields=[
                ('cod_grupo', models.SmallAutoField(primary_key=True, serialize=False, unique=True)),
                ('nome_grupo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Produtos',
            fields=[
                ('cod_produto', models.SmallAutoField(primary_key=True, serialize=False, unique=True)),
                ('nome_produto', models.CharField(max_length=155)),
                ('status_produto', models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], max_length=1)),
                ('tipo_produto', models.CharField(choices=[('M', 'Matéria Prima'), ('A', 'Produto Acabado'), ('E', 'Embalagem')], max_length=1)),
                ('valor_produto', models.IntegerField()),
                ('custo_produto', models.IntegerField()),
                ('grupo_produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='megafinance.grupo_produtos')),
            ],
        ),
        migrations.CreateModel(
            name='SubGrupo_Produtos',
            fields=[
                ('cod_subgrupo', models.SmallAutoField(primary_key=True, serialize=False, unique=True)),
                ('nome_subgrupo', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Titulo',
            fields=[
                ('cod_titulo', models.SmallAutoField(primary_key=True, serialize=False, unique=True)),
                ('status_titulo', models.CharField(blank=True, choices=[('A', 'Aberto'), ('F', 'Fechado')], default='A', max_length=1, null=True)),
                ('descricao_titulo', models.CharField(max_length=155)),
                ('pagar_receber_titulo', models.CharField(blank=True, choices=[('P', 'Contas a Pagar'), ('R', 'Contas a Receber')], default='', max_length=1, null=True)),
                ('data_inicio_titulo', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_final_titulo', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Unidade_Produtos',
            fields=[
                ('cod_unidade', models.SmallAutoField(primary_key=True, serialize=False, unique=True)),
                ('sigle_unidade', models.CharField(max_length=5)),
                ('nome_unidade', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('cod_vendedor', models.SmallAutoField(primary_key=True, serialize=False, unique=True)),
                ('status_vendedor', models.CharField(blank=True, choices=[('A', 'Ativo'), ('I', 'Inativo')], default='', max_length=1, null=True)),
                ('nome_vendedor', models.CharField(max_length=155)),
                ('comissao_vendedor', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Receitas',
            fields=[
                ('cod_receita', models.SmallAutoField(primary_key=True, serialize=False, unique=True)),
                ('nome_ficha_producao', models.CharField(max_length=155)),
                ('margem_lucro_produto_producao', models.IntegerField()),
                ('preco_custo_produto_producao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custo_produto_producao', to='megafinance.produtos')),
                ('produto_acabado_producao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cod_produto_acabado', to='megafinance.produtos')),
                ('produto_emabalagem_producao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cod_produto_emabalagem', to='megafinance.produtos')),
            ],
        ),
        migrations.CreateModel(
            name='Produtos_Receitas',
            fields=[
                ('cod_produto_receita', models.SmallAutoField(primary_key=True, serialize=False, unique=True)),
                ('quantidade_produto_receita', models.IntegerField()),
                ('cod_produto', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='megafinance.produtos')),
                ('cod_receita', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='megafinance.receitas')),
            ],
        ),
        migrations.AddField(
            model_name='produtos',
            name='subgrupo_produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='megafinance.subgrupo_produtos'),
        ),
        migrations.AddField(
            model_name='produtos',
            name='unidade_produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='megafinance.unidade_produtos'),
        ),
        migrations.CreateModel(
            name='Producao',
            fields=[
                ('cod_producao', models.SmallAutoField(primary_key=True, serialize=False, unique=True)),
                ('quantidade_producao', models.IntegerField()),
                ('status_producao', models.CharField(choices=[('A', 'Aberto'), ('F', 'Fechado')], max_length=1)),
                ('data_hora_inicio', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_hora_final', models.DateTimeField()),
                ('cod_receita', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='megafinance.receitas')),
            ],
        ),
        migrations.CreateModel(
            name='Pedido_Venda',
            fields=[
                ('cod_pedido_venda', models.SmallAutoField(primary_key=True, serialize=False, unique=True)),
                ('status_pedido_venda', models.CharField(blank=True, choices=[('A', 'Aberto'), ('F', 'Fechado')], default='A', max_length=1, null=True)),
                ('data_pedido_venda', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_prazo_pedido_venda', models.DateTimeField()),
                ('cliente_pedido_venda', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='megafinance.cliente')),
                ('cod_titulo', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='megafinance.titulo')),
                ('forma_pagamento_pedido_venda', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='megafinance.forma_pagamento')),
                ('vendedor_pedido_venda', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='megafinance.vendedor')),
            ],
        ),
        migrations.CreateModel(
            name='Lista_Produtos_PedVen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cod_pedido_venda', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='megafinance.pedido_venda')),
                ('codigo_produto_pedven', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cod_item', to='megafinance.produtos')),
                ('desconto_produto_pedven', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='desconto_item', to='megafinance.produtos')),
                ('nome_produto_pedven', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='nome_item', to='megafinance.produtos')),
                ('valor_produto_pedven', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='valor_item', to='megafinance.produtos')),
            ],
        ),
        migrations.CreateModel(
            name='Contas_A_Receber',
            fields=[
                ('cod_contas_a_receber', models.SmallAutoField(primary_key=True, serialize=False, unique=True)),
                ('valor_titulo_a_receber', models.PositiveIntegerField()),
                ('desconto_titulo_a_receber', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('cod_titulo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='megafinance.titulo')),
                ('nome_clinete_contas_a_pagar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nome_cliente', to='megafinance.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Contas_A_Pagar',
            fields=[
                ('cod_contas_a_pagar', models.SmallAutoField(primary_key=True, serialize=False, unique=True)),
                ('valor_titulo_a_pagar', models.PositiveIntegerField()),
                ('valor_desconto_a_pagar', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('cod_titulo', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='megafinance.titulo')),
                ('nome_fornecedor_contas_a_pagar', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nome_fornecedor_contas_a_pagar', to='megafinance.fornecedor')),
            ],
        ),
        migrations.CreateModel(
            name='Atualiza_Estoque_Producao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.IntegerField()),
                ('entrada_saida_produtos', models.CharField(choices=[('E', 'Entrada'), ('S', 'Saida')], max_length=1)),
                ('cod_producao', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='megafinance.producao')),
                ('cod_produto', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='megafinance.produtos')),
            ],
        ),
    ]
