# Generated by Django 4.0.4 on 2022-05-21 00:06

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('megafinance', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contas_a_pagar',
            name='cod_contas_a_pagar',
            field=models.SmallAutoField(primary_key=True, serialize=False, unique=True, verbose_name='Código Contas a Pagar'),
        ),
        migrations.AlterField(
            model_name='contas_a_pagar',
            name='cod_titulo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='megafinance.titulo', verbose_name='Código do Titulo'),
        ),
        migrations.AlterField(
            model_name='contas_a_pagar',
            name='nome_fornecedor_contas_a_pagar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nome_fornecedor_contas_a_pagar', to='megafinance.fornecedor', verbose_name='Nome fornecedor'),
        ),
        migrations.AlterField(
            model_name='contas_a_pagar',
            name='valor_desconto_a_pagar',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Desconto do Titulo'),
        ),
        migrations.AlterField(
            model_name='contas_a_pagar',
            name='valor_titulo_a_pagar',
            field=models.PositiveIntegerField(verbose_name='Valor do Titulo'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='bairro_endereco_fornecedor',
            field=models.CharField(max_length=155, verbose_name='Bairro'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='cnpj_fornecedor',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='CNPJ do Fornecedor'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='cod_fornecedor',
            field=models.SmallAutoField(primary_key=True, serialize=False, unique=True, verbose_name='Código do Fornecedor'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='complemento_endereco_fornecedor',
            field=models.CharField(max_length=155, verbose_name='Complemento'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='cpf_fornecedor',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='CPF do Fornecedor'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='email_fornecedor',
            field=models.EmailField(max_length=254, verbose_name='Email do Fornecedor'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='nome_fornecedor',
            field=models.CharField(max_length=155, verbose_name='Nome do Fornecedor'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='numero_endereco_fornecedor',
            field=models.CharField(max_length=10, verbose_name='Numero de Endereço'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='rua_endereco_fornecedor',
            field=models.CharField(max_length=155, verbose_name='Endereço do Fornecedor'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='status_fornecedor',
            field=models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], default='', max_length=1, verbose_name='Status do Fornecedor'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='telefone1_fornecedor',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Telefone Fixo'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='telefone2_fornecedor',
            field=models.CharField(blank=True, max_length=25, null=True, verbose_name='Telefone Celular'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='tipo_fornecedor',
            field=models.CharField(choices=[('F', 'Pessoa Fisica'), ('J', 'Pessoa Juridica')], default='', max_length=1, verbose_name='Tipo do Fornecedor'),
        ),
        migrations.AlterField(
            model_name='titulo',
            name='cod_titulo',
            field=models.SmallAutoField(primary_key=True, serialize=False, unique=True, verbose_name='Código do Titulo'),
        ),
        migrations.AlterField(
            model_name='titulo',
            name='data_final_titulo',
            field=models.DateTimeField(verbose_name='Data final do Titulo'),
        ),
        migrations.AlterField(
            model_name='titulo',
            name='data_inicio_titulo',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data de Inicio do Titulo'),
        ),
        migrations.AlterField(
            model_name='titulo',
            name='descricao_titulo',
            field=models.CharField(max_length=155, verbose_name='Descrição do Titulo'),
        ),
        migrations.AlterField(
            model_name='titulo',
            name='pagar_receber_titulo',
            field=models.CharField(blank=True, choices=[('P', 'Contas a Pagar'), ('R', 'Contas a Receber')], default='', max_length=1, null=True, verbose_name='Pagar ou Receber'),
        ),
        migrations.AlterField(
            model_name='titulo',
            name='status_titulo',
            field=models.CharField(blank=True, choices=[('A', 'Aberto'), ('F', 'Fechado')], default='A', max_length=1, null=True, verbose_name='Status do Fornecedor'),
        ),
    ]
