# Generated by Django 4.0.4 on 2022-05-21 00:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('megafinance', '0002_alter_contas_a_pagar_cod_contas_a_pagar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='titulo',
            name='status_titulo',
            field=models.CharField(blank=True, choices=[('A', 'Aberto'), ('F', 'Fechado')], default='A', max_length=1, null=True, verbose_name='Status do Titulo'),
        ),
    ]
