# Generated by Django 4.0.4 on 2022-05-21 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('megafinance', '0003_alter_titulo_status_titulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='cep_fornecedor',
            field=models.CharField(default='', max_length=9, verbose_name='CEP'),
        ),
        migrations.AlterField(
            model_name='fornecedor',
            name='complemento_endereco_fornecedor',
            field=models.CharField(blank=True, max_length=155, null=True, verbose_name='Complemento'),
        ),
    ]
