# Generated by Django 4.0.4 on 2022-05-21 01:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('megafinance', '0004_fornecedor_cep_fornecedor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atualiza_estoque_producao',
            name='cod_producao',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='megafinance.producao', verbose_name='Código da Producão'),
        ),
        migrations.AlterField(
            model_name='atualiza_estoque_producao',
            name='cod_produto',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='megafinance.produtos', verbose_name='Código do Produto'),
        ),
        migrations.AlterField(
            model_name='atualiza_estoque_producao',
            name='entrada_saida_produtos',
            field=models.CharField(choices=[('E', 'Entrada'), ('S', 'Saida')], max_length=1, verbose_name='Entrada ou Saida'),
        ),
        migrations.AlterField(
            model_name='atualiza_estoque_producao',
            name='quantidade',
            field=models.IntegerField(verbose_name='Quantidade do produto'),
        ),
        migrations.AlterField(
            model_name='contas_a_receber',
            name='cod_contas_a_receber',
            field=models.SmallAutoField(primary_key=True, serialize=False, unique=True, verbose_name='Código Contas a Receber'),
        ),
        migrations.AlterField(
            model_name='contas_a_receber',
            name='cod_titulo',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='megafinance.titulo', verbose_name='Código do Titulo'),
        ),
        migrations.AlterField(
            model_name='contas_a_receber',
            name='desconto_titulo_a_receber',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Desconto Titulo a Receber'),
        ),
        migrations.AlterField(
            model_name='contas_a_receber',
            name='nome_clinete_contas_a_pagar',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='nome_cliente', to='megafinance.cliente', verbose_name='Nome do Cliente'),
        ),
        migrations.AlterField(
            model_name='contas_a_receber',
            name='valor_titulo_a_receber',
            field=models.PositiveIntegerField(verbose_name='Valor Titulo a Receber'),
        ),
        migrations.AlterField(
            model_name='forma_pagamento',
            name='cod_forma_pagamento',
            field=models.SmallAutoField(primary_key=True, serialize=False, unique=True, verbose_name='Código de Forma de Pagamento'),
        ),
        migrations.AlterField(
            model_name='forma_pagamento',
            name='estilo_forma_pagamento',
            field=models.CharField(blank=True, choices=[('A', 'A vista'), ('P', 'A prazo')], default='', max_length=1, null=True, verbose_name='Tipo da Forma de Pagamento'),
        ),
        migrations.AlterField(
            model_name='forma_pagamento',
            name='nome_forme_pagamento',
            field=models.CharField(max_length=50, verbose_name='Nome da Forma de Pagamento'),
        ),
        migrations.AlterField(
            model_name='forma_pagamento',
            name='prazo_forma_pagamento',
            field=models.IntegerField(verbose_name='Prazo da Forma de Pagamento'),
        ),
        migrations.AlterField(
            model_name='grupo_produtos',
            name='cod_grupo',
            field=models.SmallAutoField(primary_key=True, serialize=False, unique=True, verbose_name='Código do Grupo'),
        ),
        migrations.AlterField(
            model_name='grupo_produtos',
            name='nome_grupo',
            field=models.CharField(max_length=50, verbose_name='Nome do Grupo'),
        ),
        migrations.AlterField(
            model_name='lista_produtos_pedven',
            name='cod_pedido_venda',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='megafinance.pedido_venda', verbose_name='Código do Pedido de Venda'),
        ),
        migrations.AlterField(
            model_name='lista_produtos_pedven',
            name='codigo_produto_pedven',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='cod_item', to='megafinance.produtos', verbose_name='Código do Produto'),
        ),
        migrations.AlterField(
            model_name='lista_produtos_pedven',
            name='desconto_produto_pedven',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='desconto_item', to='megafinance.produtos', verbose_name='Desconto do Produto'),
        ),
        migrations.AlterField(
            model_name='lista_produtos_pedven',
            name='nome_produto_pedven',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='nome_item', to='megafinance.produtos', verbose_name='Nome do Produto'),
        ),
        migrations.AlterField(
            model_name='lista_produtos_pedven',
            name='valor_produto_pedven',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='valor_item', to='megafinance.produtos', verbose_name='Valor do Produto'),
        ),
        migrations.AlterField(
            model_name='pedido_venda',
            name='cliente_pedido_venda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='megafinance.cliente', verbose_name='Cliente'),
        ),
        migrations.AlterField(
            model_name='pedido_venda',
            name='cod_pedido_venda',
            field=models.SmallAutoField(primary_key=True, serialize=False, unique=True, verbose_name='Código do Pedido de Venda'),
        ),
        migrations.AlterField(
            model_name='pedido_venda',
            name='cod_titulo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='megafinance.titulo', verbose_name='Código do Titulo'),
        ),
        migrations.AlterField(
            model_name='pedido_venda',
            name='data_pedido_venda',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data do pedido'),
        ),
        migrations.AlterField(
            model_name='pedido_venda',
            name='data_prazo_pedido_venda',
            field=models.DateTimeField(verbose_name='Prazo de entrega'),
        ),
        migrations.AlterField(
            model_name='pedido_venda',
            name='forma_pagamento_pedido_venda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='megafinance.forma_pagamento', verbose_name='Forma de Pagamento'),
        ),
        migrations.AlterField(
            model_name='pedido_venda',
            name='status_pedido_venda',
            field=models.CharField(blank=True, choices=[('A', 'Aberto'), ('F', 'Fechado')], default='A', max_length=1, null=True, verbose_name='Status do Pedido de Venda'),
        ),
        migrations.AlterField(
            model_name='pedido_venda',
            name='vendedor_pedido_venda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='megafinance.vendedor', verbose_name='Vendedor'),
        ),
        migrations.AlterField(
            model_name='producao',
            name='cod_producao',
            field=models.SmallAutoField(primary_key=True, serialize=False, unique=True, verbose_name='Código da Produção'),
        ),
        migrations.AlterField(
            model_name='producao',
            name='cod_receita',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='megafinance.receitas', verbose_name='Código da Receita'),
        ),
        migrations.AlterField(
            model_name='producao',
            name='data_hora_final',
            field=models.DateTimeField(verbose_name='Data de Finalização da Produção'),
        ),
        migrations.AlterField(
            model_name='producao',
            name='data_hora_inicio',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data do Inicio da Receita'),
        ),
        migrations.AlterField(
            model_name='producao',
            name='quantidade_producao',
            field=models.IntegerField(verbose_name='Quantidade de producação'),
        ),
        migrations.AlterField(
            model_name='producao',
            name='status_producao',
            field=models.CharField(choices=[('A', 'Aberto'), ('F', 'Fechado')], max_length=1, verbose_name='Status da Produção'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='cod_produto',
            field=models.SmallAutoField(primary_key=True, serialize=False, unique=True, verbose_name='Código do Produto'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='custo_produto',
            field=models.IntegerField(verbose_name='Custo do Produto'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='grupo_produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='megafinance.grupo_produtos', verbose_name='Grupo'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='nome_produto',
            field=models.CharField(max_length=155, verbose_name='Nome do Produto'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='status_produto',
            field=models.CharField(choices=[('A', 'Ativo'), ('I', 'Inativo')], max_length=1, verbose_name='Status do Produto'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='subgrupo_produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='megafinance.subgrupo_produtos', verbose_name='Subgrupo'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='tipo_produto',
            field=models.CharField(choices=[('M', 'Matéria Prima'), ('A', 'Produto Acabado'), ('E', 'Embalagem')], max_length=1, verbose_name='Tipo do Produto'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='unidade_produto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='megafinance.unidade_produtos', verbose_name='Unidade do Produto'),
        ),
        migrations.AlterField(
            model_name='produtos',
            name='valor_produto',
            field=models.IntegerField(verbose_name='Valor do Produto'),
        ),
        migrations.AlterField(
            model_name='produtos_receitas',
            name='cod_produto',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='megafinance.produtos', verbose_name='Código do Produto'),
        ),
        migrations.AlterField(
            model_name='produtos_receitas',
            name='cod_produto_receita',
            field=models.SmallAutoField(primary_key=True, serialize=False, unique=True, verbose_name='Código da Lista de Produtos'),
        ),
        migrations.AlterField(
            model_name='produtos_receitas',
            name='cod_receita',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='megafinance.receitas', verbose_name='Código da Receita'),
        ),
        migrations.AlterField(
            model_name='produtos_receitas',
            name='quantidade_produto_receita',
            field=models.IntegerField(verbose_name='Quantidade do Produto'),
        ),
        migrations.AlterField(
            model_name='receitas',
            name='cod_receita',
            field=models.SmallAutoField(primary_key=True, serialize=False, unique=True, verbose_name='Código da Receita'),
        ),
        migrations.AlterField(
            model_name='receitas',
            name='margem_lucro_produto_producao',
            field=models.IntegerField(verbose_name='Margem de Lucro'),
        ),
        migrations.AlterField(
            model_name='receitas',
            name='nome_ficha_producao',
            field=models.CharField(max_length=155, verbose_name='Nome da Ficha de Produção'),
        ),
        migrations.AlterField(
            model_name='receitas',
            name='preco_custo_produto_producao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custo_produto_producao', to='megafinance.produtos', verbose_name='Custo da Produção'),
        ),
        migrations.AlterField(
            model_name='receitas',
            name='produto_acabado_producao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cod_produto_acabado', to='megafinance.produtos', verbose_name='Produto acabado'),
        ),
        migrations.AlterField(
            model_name='receitas',
            name='produto_emabalagem_producao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cod_produto_emabalagem', to='megafinance.produtos', verbose_name='Produto embalagem'),
        ),
        migrations.AlterField(
            model_name='subgrupo_produtos',
            name='cod_subgrupo',
            field=models.SmallAutoField(primary_key=True, serialize=False, unique=True, verbose_name='Código de Subgrupo'),
        ),
        migrations.AlterField(
            model_name='subgrupo_produtos',
            name='nome_subgrupo',
            field=models.CharField(max_length=50, verbose_name='Nome do Subgrupo'),
        ),
        migrations.AlterField(
            model_name='unidade_produtos',
            name='cod_unidade',
            field=models.SmallAutoField(primary_key=True, serialize=False, unique=True, verbose_name='Código Unidade'),
        ),
        migrations.AlterField(
            model_name='unidade_produtos',
            name='nome_unidade',
            field=models.CharField(max_length=50, verbose_name='Nome da Unidade'),
        ),
        migrations.AlterField(
            model_name='unidade_produtos',
            name='sigle_unidade',
            field=models.CharField(max_length=5, verbose_name='Sigla unidade'),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='cod_vendedor',
            field=models.SmallAutoField(primary_key=True, serialize=False, unique=True, verbose_name='Código do Vendedor'),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='comissao_vendedor',
            field=models.FloatField(verbose_name='Comissão do Vendedor'),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='nome_vendedor',
            field=models.CharField(max_length=155, verbose_name='Nome do Vendedor'),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='status_vendedor',
            field=models.CharField(blank=True, choices=[('A', 'Ativo'), ('I', 'Inativo')], default='', max_length=1, null=True, verbose_name='Status do Vendedor'),
        ),
    ]
