# Generated by Django 4.0.4 on 2022-05-23 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('megafinance', '0006_alter_cliente_email_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cnpj_cliente',
            field=models.CharField(blank=True, max_length=18, null=True, verbose_name='CNPJ'),
        ),
        migrations.AlterField(
            model_name='cliente',
            name='cpf_cliente',
            field=models.CharField(blank=True, max_length=14, null=True, verbose_name='CPF'),
        ),
    ]
