# Generated by Django 4.0.4 on 2022-05-23 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('megafinance', '0009_alter_cliente_cpf_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cpf_cliente',
            field=models.CharField(blank=True, max_length=14, null=True, unique=True, verbose_name='CPF'),
        ),
    ]
