# Generated by Django 4.0.4 on 2022-05-23 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('megafinance', '0010_alter_cliente_cpf_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='cnpj_cliente',
            field=models.CharField(blank=True, max_length=18, null=True, unique=True, verbose_name='CNPJ'),
        ),
    ]
