# Generated by Django 4.0.4 on 2022-05-24 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('megafinance', '0011_alter_cliente_cnpj_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='email_fornecedor',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email do Fornecedor'),
        ),
        migrations.AlterField(
            model_name='titulo',
            name='data_final_titulo',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Data final do Titulo'),
        ),
    ]
