# Generated by Django 4.0.4 on 2022-05-25 21:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('megafinance', '0013_alter_contas_a_pagar_cod_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contas_a_pagar',
            name='nome_fornecedor_contas_a_pagar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='nome_fornecedor_contas_a_pagar', to='megafinance.fornecedor', verbose_name='Nome fornecedor'),
        ),
    ]
