# Generated by Django 4.0.4 on 2022-05-25 21:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('megafinance', '0014_alter_contas_a_pagar_nome_fornecedor_contas_a_pagar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contas_a_pagar',
            name='valor_desconto_a_pagar',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Desconto do Titulo'),
        ),
    ]
