# Generated by Django 4.0.4 on 2022-05-26 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('megafinance', '0015_alter_contas_a_pagar_valor_desconto_a_pagar'),
    ]

    operations = [
        migrations.AddField(
            model_name='fornecedor',
            name='cidade_endereco_fornecedor',
            field=models.CharField(default='', max_length=155, verbose_name='Cidade do Fornecedor'),
        ),
    ]
