# Generated by Django 4.0.4 on 2022-05-27 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('megafinance', '0016_fornecedor_cidade_endereco_fornecedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contas_a_pagar',
            name='nome_fornecedor_contas_a_pagar',
            field=models.SmallIntegerField(verbose_name='Nome fornecedor'),
        ),
    ]
