# Generated by Django 4.0.4 on 2022-05-27 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('megafinance', '0019_alter_contas_a_pagar_nome_fornecedor_contas_a_pagar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='cidade_endereco_fornecedor',
            field=models.CharField(default='', max_length=154, verbose_name='Cidade do Fornecedor'),
        ),
    ]
