# Generated by Django 4.0.4 on 2022-05-27 01:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('megafinance', '0020_alter_fornecedor_cidade_endereco_fornecedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fornecedor',
            name='cidade_endereco_fornecedor',
            field=models.CharField(default='', max_length=155, verbose_name='Cidade do Fornecedor'),
        ),
    ]
