# Generated by Django 4.0.4 on 2022-05-27 02:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('megafinance', '0021_alter_fornecedor_cidade_endereco_fornecedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contas_a_pagar',
            name='nome_fornecedor_contas_a_pagar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='megafinance.fornecedor', verbose_name='Nome fornecedor'),
        ),
    ]
