# Generated by Django 4.0.4 on 2022-05-27 02:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('megafinance', '0022_alter_contas_a_pagar_nome_fornecedor_contas_a_pagar'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contas_a_pagar',
            options={'managed': False},
        ),
    ]
