# Generated by Django 4.0.4 on 2022-05-27 02:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('megafinance', '0023_alter_contas_a_pagar_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contas_a_pagar',
            options={},
        ),
    ]
