# Generated by Django 4.0.4 on 2022-05-27 12:30

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('megafinance', '0024_alter_contas_a_pagar_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contas_a_pagar',
            name='nome_fornecedor_contas_a_pagar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='megafinance.fornecedor', verbose_name='Nome fornecedor'),
        ),
        migrations.AlterField(
            model_name='contas_a_receber',
            name='desconto_titulo_a_receber',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Desconto Titulo a Receber'),
        ),
        migrations.AlterField(
            model_name='contas_a_receber',
            name='nome_clinete_contas_a_pagar',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='megafinance.cliente', verbose_name='Nome do Cliente'),
        ),
    ]
