# Generated by Django 4.0.4 on 2022-05-27 13:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('megafinance', '0026_rename_nome_clinete_contas_a_pagar_contas_a_receber_nome_cliente_contas_a_pagar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contas_a_receber',
            old_name='nome_cliente_contas_a_pagar',
            new_name='nome_cliente_contas_a_receber',
        ),
    ]
